import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

export const metadata = {
    title: 'Terms & Conditions | Artelipi',
    description: 'Terms and Conditions for using Artelipi publishing platform.',
};

export default function TermsPage() {
    return (
        <>
            <Header />
            <div className="min-h-screen bg-white py-16">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                    <h1 className="text-5xl font-bold mb-6">Terms & Conditions</h1>
                    <p className="text-gray-600 mb-8">Last updated: December 29, 2025</p>

                    <div className="prose prose-lg max-w-none space-y-6 text-gray-700">
                        <h2 className="text-3xl font-bold mt-8 mb-4">Agreement to Terms</h2>
                        <p>
                            By accessing or using Artelipi, you agree to be bound by these Terms and Conditions.
                            If you disagree with any part of these terms, you may not use our service.
                        </p>

                        <h2 className="text-3xl font-bold mt-8 mb-4">User Accounts</h2>
                        <p>
                            When you create an account with us, you must provide accurate and complete information.
                            You are responsible for maintaining the security of your account and password.
                        </p>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Content Guidelines</h2>
                        <p>As a user of Artelipi, you agree that your content will:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Not violate any laws or regulations</li>
                            <li>Not infringe on intellectual property rights</li>
                            <li>Not contain harmful, offensive, or inappropriate material</li>
                            <li>Not contain spam or misleading information</li>
                            <li>Be your original work or properly attributed</li>
                        </ul>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Content Ownership</h2>
                        <p>
                            You retain all rights to the content you publish on Artelipi. By publishing content,
                            you grant Artelipi a non-exclusive license to display, distribute, and promote your
                            content on our platform.
                        </p>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Editorial Standards</h2>
                        <p>
                            All articles on Artelipi must follow our editorial structure:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>A clear, descriptive headline (mandatory)</li>
                            <li>An automatically generated byline</li>
                            <li>Well-formatted content</li>
                        </ul>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Content Moderation</h2>
                        <p>
                            We reserve the right to remove any content that violates these terms or is deemed
                            inappropriate. We may suspend or terminate accounts that repeatedly violate our guidelines.
                        </p>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Prohibited Uses</h2>
                        <p>You may not use Artelipi to:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Harass, abuse, or harm others</li>
                            <li>Impersonate others or provide false information</li>
                            <li>Distribute malware or harmful code</li>
                            <li>Attempt to gain unauthorized access to our systems</li>
                            <li>Use automated systems to access the platform</li>
                        </ul>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Disclaimer</h2>
                        <p>
                            Artelipi is provided "as is" without warranties of any kind. We do not guarantee that
                            the service will be uninterrupted, secure, or error-free.
                        </p>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Limitation of Liability</h2>
                        <p>
                            Artelipi shall not be liable for any indirect, incidental, special, or consequential
                            damages arising from your use of the platform.
                        </p>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Changes to Terms</h2>
                        <p>
                            We reserve the right to modify these terms at any time. We will notify users of any
                            material changes by posting the new terms on this page.
                        </p>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Termination</h2>
                        <p>
                            We may terminate or suspend your account immediately, without prior notice, for any
                            violation of these Terms and Conditions.
                        </p>

                        <h2 className="text-3xl font-bold mt-8 mb-4">Contact</h2>
                        <p>
                            If you have any questions about these Terms, please contact us at{' '}
                            <a href="mailto:legal@artelipi.com" className="text-blue-600 hover:text-blue-700">
                                legal@artelipi.com
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    );
}
